#!/usr/bin/env bash
set -e
bin=$DAPP_OUT/${1?missing contract name}.bin
type=$(seth --abi-constructor <"$DAPP_OUT/$1.abi")
ADDRESS=`(set -x; seth send --create "$bin" "${type/constructor/$1}" "${@:2}")`
echo $ADDRESS
dapp objects `seth chain` $1 $ADDRESS